export enum PermissionType {
  ListIngredients = "ListIngredients",
  CreateIngredient = "CreateIngredient",
  EditIngredient = "EditIngredient",
  CurateIngredient = "CurateIngredient",
  DeleteIngredient = "DeleteIngredient",
  ListSpecs = "ListSpecs",
  CreateSpec = "CreateSpec",
  EditSpec = "EditSpec",
  CurateSpec = "CurateSpec",
  DeleteSpec = "DeleteSpec",
  EditUser = "EditUser",
  AddReview = "AddReview",
  ModerateReviews = "ModerateReviews",
  ModifyUserPermissions = "ModifyUserPermissions",
}
